[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://biblioteca-virtual-api.onrender.com/api"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
