services:
  - type: web
    name: biblioteca-virtual-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: biblioteca-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: biblioteca-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: biblioteca-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: biblioteca-db
          property: database
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: biblioteca-db
    plan: free
    databaseName: biblioteca_virtual
    user: biblioteca_user
